VIP-537: Set up external-geospatial-feature validation
votinginfoproject/data-processor pull request #362
Opened 2022-06-15 15:13 UTC by alice-dw

2022-06-15 17:31 UTC, danny-pease commented
Status: Liz and I are futzing with the tickets/scopes for the GIS work and this PR may need to stretch to accommodate what we learn from that process. We need to nail this down before merging/reviewing, will follow up wiht an update soon. Thanks!

2022-06-20 13:09 UTC, danny-pease commented
Update: _mostly_ sure that this review doesn't need to change as a result of ticket rehashing. Will update again tomorrow, by when I will know for sure.

2022-06-23 14:50 UTC, dwxander commented on test/vip/data_processor/validation/v6/external_geospatial_feature_test.clj
> +    (are [path]
General q for validations: is there a difference between doing multiple `(are` statements and putting multiple paths in one statement? I noticed both in existing tests.

2022-06-23 14:50 UTC, dwxander commented on test-resources/xml/v6-external-geospatial-feature.xml
> +  <!-- 1. missing ExternalFileId -->
putting the indices in is such a good idea

2022-06-23 14:50 UTC, dwxander commented on test/vip/data_processor/validation/v6/external_geospatial_feature_test.clj
> +      (is (contains-error? errors
Does the empty FeatureIdentifier index create a missing path that this test would expect?

2022-06-27 14:52 UTC, danny-pease approved these changes
lgtm!

2022-07-01 20:44 UTC, lizstarin requested changes
Sorry this is late! Don't know how I missed it. 
Comments mostly around the nesting of `ExternalGeospatialFeature` inside `SpatialBoundary`.

2022-07-01 20:44 UTC, lizstarin commented on test-resources/xml/v6_sample_feed.xml
> +  <ExternalGeospatialFeature>
This element will need its own id attribute as well! i.e. `<ExternalGeospatialFeature id="exgf01">`

2022-07-01 20:44 UTC, lizstarin commented on test-resources/xml/v6_sample_feed.xml
>    <SpatialBoundary>
Actually, this one nested inside `SpatialBoundary` is what you want; I don't think you need to repeat `ExternalGeospatialFeature` as a top-level element.

2022-07-01 20:44 UTC, lizstarin commented on test-resources/xml/v6_sample_feed.xml
>    <SpatialBoundary>
(and make sure to give the `SpatialBoundary` an id attribute as well)

2022-07-01 20:44 UTC, lizstarin commented on test/vip/data_processor/validation/v6/external_geospatial_feature_test.clj
> +      (is (contains-error? errors
Yes, empty elements simply don't become entries in the ltree table, so it's the same as if the element weren't there at all.

2022-07-01 20:44 UTC, lizstarin commented on test-resources/xml/v6-external-geospatial-feature.xml
> +  <!-- 0. all fields populated -->
I like the way you've organized this file.

2022-07-01 20:44 UTC, lizstarin commented on test/vip/data_processor/validation/v6/external_geospatial_feature_test.clj
> +                            :identifier "VipObject.0.ExternalGeospatialFeature.1.ExternalFileId"
To continue the above conversation about nesting `ExternalGeospatialFeature`, I believe it's _always_ nested inside `SpatialBoundary`, in which case you should do the same in your "bad" XML as well.

2022-07-01 20:44 UTC, lizstarin commented on src/vip/data_processor/validation/v6/external_geospatial_feature.clj
> +
You'd expect to see `ExternalGeospatialFeature` inside a `SpatialBoundary`, I believe, which would change these paths and indices.

2022-07-05 16:04 UTC, alice-dw commented on src/vip/data_processor/validation/v6/external_geospatial_feature.clj
> +
fixed!

2022-07-05 16:18 UTC, alice-dw commented on test/vip/data_processor/validation/v6/external_geospatial_feature_test.clj
> +    (are [path]
i think this may be one? https://github.com/votinginfoproject/data-processor/blob/staging/test/vip/data_processor/validation/v5/candidate_test.clj#L21-L30

2022-07-05 16:26 UTC, lizstarin commented on test/vip/data_processor/validation/v6/external_geospatial_feature_test.clj
> +    (are [path]
Ah. So the trick is that `are` is already a shortcut for multiple `is` statements:https://clojure.github.io/clojure/clojure.test-api.html#clojure.test/are

So if the assertions are the same, then using multiple `are` statements is just an organizational choice, afaik.

2022-07-05 16:29 UTC, lizstarin commented on test/vip/data_processor/validation/v6/external_geospatial_feature_test.clj
> +    (are [path]
(and if it's just one path, you could use `is`)

2022-07-05 16:30 UTC, alice-dw commented on test/vip/data_processor/validation/v6/external_geospatial_feature_test.clj
> +    (are [path]
i see. is it preferable then to combine multiple paths into one statement? if i'm using `are` already anyways

2022-07-05 16:31 UTC, lizstarin commented on test/vip/data_processor/validation/v6/external_geospatial_feature_test.clj
> +    (are [path]
I think that depends entirely on what the situation demands in terms of code conciseness vs. readability.

2022-07-05 21:24 UTC, alice-dw commented
@lizstarin ready for re-review!

2022-07-12 17:47 UTC, lizstarin requested changes
More `id` attributes.

2022-07-12 17:47 UTC, lizstarin commented on test-resources/xml/v6-external-geospatial-feature.xml
> +  <!-- 1. missing ExternalFileId -->
I would add `id` attributes to `ExternalGeospatialFeature` as well.

2022-07-12 17:54 UTC, lizstarin approved these changes
🌐

2022-07-12 17:57 UTC, merged